// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeilingAPI.Data;

#nullable disable

namespace VeilingAPI.Migrations
{
    [DbContext(typeof(VeilingDbContext))]
    [Migration("20251030055249_AddProducten")]
    partial class AddProducten
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeilingAPI.Models.Gebruiker", b =>
                {
                    b.Property<int>("gebruiker_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gebruiker_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("gebruiker_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("inloggen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("registreren")
                        .HasColumnType("datetime2");

                    b.Property<string>("wachtwoord")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("gebruiker_id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Gebruikers", (string)null);

                    b.HasDiscriminator<string>("gebruiker_type").HasValue("Gebruiker");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VeilingAPI.Models.Product", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_id"));

                    b.Property<DateTime>("aangemaakt_op")
                        .HasColumnType("datetime2");

                    b.Property<string>("beschrijving")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("prijs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("verkoper_id")
                        .HasColumnType("int");

                    b.Property<int>("voorraad")
                        .HasColumnType("int");

                    b.HasKey("product_id");

                    b.HasIndex("verkoper_id");

                    b.ToTable("Producten", (string)null);
                });

            modelBuilder.Entity("VeilingAPI.Models.Koper", b =>
                {
                    b.HasBaseType("VeilingAPI.Models.Gebruiker");

                    b.Property<string>("bedrijfsnaam")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("bedrijfsnaam");

                    b.Property<string>("btw_nummer")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("btw_nummer");

                    b.Property<string>("kvk")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("kvk");

                    b.Property<string>("leveradres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("rekening_nummer")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)")
                        .HasColumnName("rekening_nummer");

                    b.Property<string>("telefoon")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefoon");

                    b.HasDiscriminator().HasValue("Koper");
                });

            modelBuilder.Entity("VeilingAPI.Models.Verkoper", b =>
                {
                    b.HasBaseType("VeilingAPI.Models.Gebruiker");

                    b.Property<string>("bedrijfsadres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("bedrijfsnaam")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("bedrijfsnaam");

                    b.Property<string>("btw_nummer")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("btw_nummer");

                    b.Property<string>("kvk")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("kvk");

                    b.Property<string>("rekening_nummer")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)")
                        .HasColumnName("rekening_nummer");

                    b.Property<string>("telefoon")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefoon");

                    b.HasDiscriminator().HasValue("Verkoper");
                });

            modelBuilder.Entity("VeilingAPI.Models.Product", b =>
                {
                    b.HasOne("VeilingAPI.Models.Verkoper", "Verkoper")
                        .WithMany()
                        .HasForeignKey("verkoper_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verkoper");
                });
#pragma warning restore 612, 618
        }
    }
}
